version: '3.8'
services:
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_DATABASE: first-responder
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  db-tests:
    image: mariadb:latest
    container_name: db-tests
    environment:
      MYSQL_USER: operator
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: first-responder-tests
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data_tests:/var/lib/mysql
      - ./app/utils/create_tests_base.sql:/create_tests_base.sql

  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mariadb_data:
  mariadb_data_tests:
