version: '3.8'
services:
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_DATABASE: first-responder
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mariadb_data:
  mariadb_data_tests:
