# Generated by Django 4.2.5 on 2023-10-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('coordinates_latitude', models.FloatField()),
                ('coordinates_longitude', models.FloatField()),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='back.buildingtype')),
            ],
        ),
    ]
