# Generated by Django 4.2.5 on 2023-10-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_scenariotype_stafftype_vehicletype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='name',
        ),
    ]
