# Generated by Django 4.2.5 on 2023-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_remove_call_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='mission_status',
            field=models.CharField(auto_created='not_started', choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20),
        ),
    ]
