# Generated by Django 4.2.5 on 2023-10-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_call_mission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='call',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_on_scene', to='back.call'),
        ),
    ]
